### ISSUE TITLE
Explain 'workers' and 'worker-connections'

### ISSUE THREAD

**Issue by peterbe** [mozilla/antenna#23]
The README suggests, to get started, that you run with `--workers=1` and `--worker-connections=4`. Sure. But once going into benchmarking or production, you might want to more guidance on what these numbers mean and guidance on how to set the best possible numbers. 

Also, perhaps there ought to be guidance to explain how to set the number of workers to be that of the number of CPUs the machine has.

**Comment by willkg** [comment]
Antenna is only targeted for Mozilla and us specifically. I plan on documenting dev environment things, but not "how to run this in production". If that changes at some point in the future, we can improve things then, but I'm not planning to spend time on it in this phase.

If you have better explanations for the README or some other part of the docs, let me know and I can include them or you can do a PR--whichever is easiest for you.

**Comment by peterbe** [comment]
At some point we have to tell CloudOps; Please install this. Do we have an answer ready for their questions about # workers and # worker connections?

**Comment by willkg** [comment]
I don't have any ready answers for anything about how this should get set up in production because we're still pretty early on in development and there's nothing to benchmark, yet.

When we've got this implemented enough to do load testing and benchmarking and such, we'll know more about those numbers. We can work out the rest with @jdotpz when we get there since what we use for those numbers will depend on how we want to set this up in production.

I claim that'll all be very Mozilla-centric. Given that, it's not documentation I want to write or maintain. That's what I'm thinking right now. Maybe I'll change my mind in a month when things gel or other needs become more apparent?

**Comment by willkg** [comment]
Antenna has changed substantially since this issue was opened and it's not relevant anymore. So I'm going to close it out.
